theme: jekyll-rtd-theme
title: OpenShift Migration Best Practices
repo_url: 'https://github.com/redhat-cop/openshift-migration-best-practices'
baseurl: '/openshift-migration-best-practices/'

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-github-metadata
